### ISSUE TITLE
visualisation des equations

### ISSUE THREAD

**Issue by thesylio** [MicrosoftDocs/quantum-docs-pr.fr-FR#1]
La version française (https://docs.microsoft.com/fr-fr/quantum/concepts/multiple-qubits) de la documentation n'affiche pas correctement les équations, le problème est présent peu importe mon navigateur (Chrome ou Edge)...

J'ai essayé avec la version US (https://docs.microsoft.com/en-us/quantum/concepts/multiple-qubits) et là pas de soucis.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6516e6bf-4cd0-2d9b-4d18-565d7dbc38b6
* Version Independent ID: a5b54d5e-8b9a-f7d5-2dac-ecd515478ba5
* Content: [Plusieurs qubits - Microsoft Quantum](https://docs.microsoft.com/fr-fr/quantum/concepts/multiple-qubits#feedback)
* Content Source: [articles/concepts/multiple-qubits.md](https://github.com/MicrosoftDocs/quantum-docs-pr.fr-FR/blob/live-sxs/articles/concepts/multiple-qubits.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @thesylio
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @thesylio,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/quantum-docs-pr/issues/752.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
